### PR TITLE
fix bugs in viz code

### LINKED ISSUE #15: Some bugs in visualization
I found there are some bugs in viz code.
- `visualizer` will generate two same pictures
- when the model name is too long, it will exceed the box
- the legend doesn't provide enough information.
I'll fix them asap

### PR DESCRIPTION
**Pull request by TheFatBlue**
fix bugs mentioned in #15

### CODE REVIEW

**Comment by TomasAndersonFang** [comment]
@TheFatBlue For your solution, it seems you only add the width of the picture, maybe you could check the length of the model name?

**Comment by TheFatBlue** [comment]
for line 114, I adjust the position of the title by changing x from `x="300"` to `x="400"`, this way the title will be fully displayed in the image.

**Comment by TomasAndersonFang** [comment]
> for line 114, I adjust the position of the title by changing x from `x="300"` to `x="400"`, this way the title will be fully displayed in the image.

I see.

**Comment by TomasAndersonFang** [comment]
> > for line 114, I adjust the position of the title by changing x from `x="300"` to `x="400"`, this way the title will be fully displayed in the image.
> 
> I see.

Same question: if the model name is very long, does your setting still work well?

**Comment by TomasAndersonFang** [comment]
> > > for line 114, I adjust the position of the title by changing x from `x="300"` to `x="400"`, this way the title will be fully displayed in the image.
> > 
> > 
> > I see.
> 
> Same question: if the model name is very long, does your setting still work well?

I check some LLMs' name in HF models hub, it seems they are not very long.

**Review by TomasAndersonFang — APPROVED** [review]
good fixing.

**Comment by TheFatBlue** [comment]
> > > for line 114, I adjust the position of the title by changing x from `x="300"` to `x="400"`, this way the title will be fully displayed in the image.
> > 
> > 
> > I see.
> 
> Same question: if the model name is very long, does your setting still work well?

Maybe not, I can reduce font size to fix this if necessary.

**Comment by TomasAndersonFang** [comment]
此issue已迁移到新仓库: https://github.com/safeai4code/RobustEval-CLM/issues/28

**Comment by TomasAndersonFang** [comment]
This issue has been migrated to the new repository: https://github.com/safeai4code/RobustEval-CLM/issues/28

**Pull request merged**
