### PR TITLE
Add support for visualize the results

### LINKED ISSUE #5: Integrate visualization into our project
HI @TheFatBlue,

Recently, you implemented visualization for our experimental results personally, it's great if you could integrate your implementation into this project, which will help it more useful :)

### PR DESCRIPTION
**Pull request by TheFatBlue**
Now, when run the script, user can visualize the results in the format of Venn diagram by setting `--visualization` in the command line. The results will be saved to the same folder as the other results.
btw, environment should be updated before utilizing this function.

### CODE REVIEW

**Comment by TomasAndersonFang** [comment]
@TheFatBlue Your code looks good to me. Just make sure again, did u test your code locally by creating a python env from scratch?

**Comment by TheFatBlue** [comment]
Yes, I create a new env using updated `setup.py` by running `pip install -e .`. Everything is good and I test the new function along with original function in this env, they all work well.

**Comment by TomasAndersonFang** [comment]
> Yes, I create a new env using updated `setup.py` by running `pip install -e .`. Everything is good and I test the new function along with original function in this env, they all work well.

That's great, marged!

**Review by TomasAndersonFang — COMMENTED** [review]
Good job.

**Comment by TomasAndersonFang** [comment]
此issue已迁移到新仓库: https://github.com/safeai4code/RobustEval-CLM/issues/30

**Comment by TomasAndersonFang** [comment]
This issue has been migrated to the new repository: https://github.com/safeai4code/RobustEval-CLM/issues/30

**Pull request merged**
